<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <title>Politicas de privacidade</title>
        <link rel="stylesheet" type="text/css" href="site.css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="adendo_politicas_geral">

            <div class="adendo_politicas_topo">
                <a href="index.php"><img src="imagens/seta-esquerda.png"></a>
                <a href="index.php">Voltar para Home</a>
            </div>

            <div id="adendo_img">
                <img src="imagens/logoalien.png">
            </div>

            <div id="adendo_politicas_info">
                <h3>Aviso de Privacidade no Brasil</h3>
                <p>Data de vigência: 26 de janeiro de 2021</p>
                <p>Última modificação: 28 de dezembro de 2020</p>
            </div>

            <div id="adendo_info_conteudo">
                <p>Este Aviso de Privacidade no Brasil reforça as informações contidas na Política de Privacidade e na Política de Cookies e de Anúncios da Pizza Hut International, LLC  (“Pizza Hut”, “nós”, “nosso(s)” ou “conosco”) e se aplica somente a indivíduos residentes no Brasil ("você") e aos nossos sites, experiências online e aplicativos para dispositivos móveis Apple iOS, Windows ou Android que estão disponíveis no Brasil, incluindo www.pizzahut.com.br e qualquer outro site vinculado a este Aviso de Privacidade (“Sites”). Observação: os restaurantes da marca Pizza Hut, Sites e Serviço pertencem e são operados por franqueadas independentes em muitas localidades brasileiras. Este Aviso de Privacidade no Brasil se aplica somente ao nosso processamento de suas informações pessoais e não se aplica ao processamento de suas informações pessoais por uma franquia independente.</p>
                <p>Nossos Sites são operados no Brasil pela master franquia brasileira PHSR Master Franquia Ltda (“PHSR”, “nós”, “nosso(s)” “conosco”), sob a licença da Pizza Hut International LLC.</p>
                <p>Nossos Sites são operados no Brasil pela master franquia brasileira PHSR Master Franquia Ltda (“PHSR”, “nós”, “nosso(s)” “conosco”), sob a licença da Pizza Hut International LLC.</p>
                <p>Estamos sujeitos à Lei nº 13.709, de 14 de agosto de 2018 (“Lei Geral de Proteção de Dados Pessoais”). Este Aviso de Privacidade no Brasil foi desenvolvido de acordo com nossas obrigações de privacidade no Brasil.  Salvo disposição em contrário, todos os termos têm o mesmo significado conforme definido em nossa Política de Privacidade ou conforme definido de outra forma pela Lei Geral de Proteção de Dados Pessoais. </p>
                <h3>A MENOS QUE DISPOSTO DE OUTRA FORMA NESTE POLÍTICA OU VOCÊ NOS ACONSELHE DE OUTRA FORMA, POR MEIO DE ACESSO E USO DE NOSSOS SITES E SERVIÇO OU OUTRAS OFERTAS E FORNECIMENTO VOLUNTÁRIO DE INFORMAÇÕES PESSOAIS, VOCÊ DECLARA QUE CONSENTE COM A COLETA, O ARMAZENAMENTO, O USO, O PROCESSAMENTO E A DIVULGAÇÃO DE SUAS INFORMAÇÕES PESSOAIS CONFORME EXPLICADO NO AVISO DE PRIVACIDADE NO BRASIL E EM NOSSA POLÍTICA DE PRIVACIDADE.    </h3>
                <p>Leia atentamente os termos e condições a seguir para entender nossas opiniões e práticas em relação às suas informações pessoais e como iremos tratá-las. Ao não concordar com nossas políticas e práticas, você opta por não utilizar nosso Serviço. Ao acessar ou utilizar nosso Serviço, você concorda com este Aviso de Privacidade no Brasil e com nossa Política de Privacidade. </p>
                <p>Para efeitos deste Aviso de Privacidade no Brasil, “informações pessoais” são as informações que identificam você pessoalmente ou informações pelas quais você é identificável, como seu nome, endereço/cidade e estado/país de residência, número de telefone, endereço de e-mail ou, em alguns casos, seu endereço IP e cookies, nas situações em que essas informações podem ser combinadas com outras informações para identificá-lo.</p>
                <p><span>Base legal para o processamento de suas informações pessoais.</span> Processamos suas informações pessoais com o seu consentimento; caso o processamento seja necessário para a celebração de um contrato, como a entrega de produtos solicitados por você; para cumprir nossos interesses legítimos; ou quando nos for permitido ou sejamos obrigados a fazê-lo por lei aplicável ou por requisitos regulamentares. Quando processamos suas informações com seu consentimento, você pode alterar ou retirar seu consentimento a qualquer momento, sujeito a obrigações legais ou contratuais e notificação prévia, assinalando ou desassinalando a opção adequada fornecida nos campos em que as informações pessoais são coletadas ou entrando em contato conosco, usando as informações de contato na seção “Fale conosco” abaixo. A remoção ou alteração do seu consentimento poderá afetar nossa capacidade de fornecer a você os direitos de uso do Serviço.</p>
                <p>Se planejarmos usar ou divulgar suas informações pessoais para uma finalidade não identificada anteriormente (tanto neste Aviso de Privacidade no Brasil quanto em nossa Política de Privacidade ou separadamente), iremos informá-lo dessa finalidade antes de tal uso ou divulgação.</p>
                <p><span>Informações fornecidas por você.</span> A lista de informações que você pode nos fornecer ou que podemos coletar de ou sobre você por meio de nossos Sites e Serviço mencionados em nossa Política de Privacidade não é exaustiva, mas fornece exemplos de informações pessoais que podem ser coletadas nos Sites. Se você não deseja que a Pizza Hut colete suas informações pessoais, não as forneça a nós. Contudo, elas podem ser necessárias para prestar um Serviço para você.</p>
                <p><span>Tecnologias de Coleta Automática de Dados.</span> À medida que você navega e interage com nossos Sites, podemos usar tecnologias de coleta automática de dados para obter determinadas informações sobre seu equipamento, ações e padrões de navegação, incluindo detalhes de suas visitas aos nossos Sites e Serviço, dados de tráfego, dados de localização, registros e outros dados de comunicação e recursos que você acessa e usa nos Sites, bem como as informações sobre seu computador e conexão com a internet, incluindo seu endereço IP, sistema operacional e tipo de navegador, conforme detalhado na Seção 3 da nossa Política de Privacidade. As informações que coletamos automaticamente podem incluir informações pessoais ou podemos mantê-las ou associá-las com informações pessoais que coletamos de outras formas ou recebemos de terceiros. Isso nos ajuda a melhorar nosso Serviço e Sites e a fornecer um serviço melhor e mais personalizado.</p>
                <p><span>Retenção e Eliminação de Dados.</span> Manteremos suas informações pessoais pelo tempo razoavelmente necessário para manter o Serviço, cumprir com obrigações legais, regulatórias e contábeis e para os outros fins descritos em nossa Política de Privacidade. Nós podemos destruir, tornar anônimas e/ou reunir informações pessoais quando não mais necessárias para os fins para os quais foram coletadas, em conformidade com nossos procedimentos de backup automático e políticas de retenção de registro, de acordo com nosso interesse legítimo e legal em fazê-lo. Entre em contato conosco para saber mais detalhes sobre os períodos de retenção aplicáveis.</p>
                <h3>COMUNICAÇÕES DE MARKETING. ENVIAREMOS COMUNICAÇÕES DE MARKETING SE AUTORIZADO POR VOCÊ. AS COMUNICAÇÕES DE MARKETING QUE VOCÊ RECEBER SERÃO RELACIONADAS SOMENTE AO PROPÓSITO ESPECÍFICO PARA O QUAL VOCÊ CONSENTIU. VOCÊ PODE ENVIAR, A QUALQUER MOMENTO, UM PEDIDO DE CANCELAMENTO OU DESCADASTRAMENTO DE INSCRIÇÃO PARA NÃO RECEBER ESSAS COMUNICAÇÕES, SEGUINDO AS INSTRUÇÕES CONTIDAS NAS PRÓPRIAS COMUNICAÇÕES OU DISPONÍVEIS EM NOSSOS SITES. ENVIDAREMOS OS MELHORES ESFORÇOS PARA PROCESSAR RAPIDAMENTE TODOS OS PEDIDOS DE CANCELAMENTO OU DESCADASTRAMENTO PARA QUE VOCÊ NÃO RECEBA MAIS AS COMUNICAÇÕES DE MARKETING.</h3>
                <p>Podemos atualizar nossos Sites periodicamente e solicitar que você baixe softwares para continuar usando e acessando nossos Sites, produtos, serviços e outras ofertas, incluindo de nossas Franqueadas. Não instalaremos qualquer software em seu computador ou dispositivo sem o seu consentimento. </p>
                <p><span>Compartilhamento de informações pessoais.</span> Compartilhamos informações pessoais com terceiros na forma descrita na Seção 4 da nossa Política de Privacidade ou conforme descrito a você no momento em que solicitamos as informações. Podemos solicitar o seu consentimento (ativação ou desativação) antes de compartilhar suas informações pessoais, a menos que tenhamos outra base legal para divulgar essas informações sob a lei aplicável.  Por exemplo, divulgamos informações pessoais para prestadores de serviços terceirizados não afiliados conforme necessário para nos ajudar a administrar nossos Sites e tomamos medidas para garantir que esses terceiros não utilizarão suas informações para nenhuma finalidade que não seja fornecer os serviços administrativos pelos quais são responsáveis. Se você não deseja que nossos provedores de serviços terceirizados não afiliados tenham acesso às suas informações, não registre ou envie qualquer informação pessoal para nós. A Pizza Hut tomará medidas comercialmente razoáveis para garantir que terceiros a quem divulgamos informações pessoais tratem suas informações pessoais com segurança.</p>
                <p><span>Como controlar suas preferências de e-mail:</span> Você pode parar de receber e-mails promocionais clicando no link “descadastre-se”, fornecido nesses e-mails, assinalando ou desassinalando a opção adequada fornecida nos campos em que as informações pessoais são coletadas ou entrando em contato conosco, usando os detalhes de contato fornecidos na seção “Fale Conosco”, abaixo. Envidaremos os melhores esforços para processar rapidamente todos os pedidos de descadastramento, mas esteja ciente de que em algumas circunstâncias você pode receber mais algumas mensagens até que o cancelamento da inscrição seja processado, especialmente na data de seu descadastramento. Você também poderá ajustar determinadas preferências de e-mails fazendo login em sua conta. </p>
                <p><span>Usamos Tecnologias de Rastreamento.</span> Quando você visita nossos Sites e acessa ou usa nosso Serviço, lê nossos e-mails ou interage conosco de outra forma por meio de um computador ou dispositivo móvel, nós e nossos parceiros podemos coletar informações sobre como você acessa e usa o Serviço e informações sobre o dispositivo que você usa para acessar o Serviço.</p>
                <p>Essas informações nos permitem melhorar sua experiência como cliente. Por exemplo, nós ou terceiros com os quais trabalhamos usamos tecnologias de rastreamento para:</p>
                <ul>
                    <li>Reconhecer clientes novos e atuais;</li>
                    <li>Armazenar senhas de clientes cadastrados em nossos Sites;</li>
                    <li>Aprimorar nosso Serviço;</li>
                    <li>Oferecer anúncios publicitários personalizados e com base nos seus interesses pessoais (consulte abaixo para obter mais informações a respeito dos anúncios personalizados).</li>
                    <li>Observar os hábitos e as atividades de navegação em diversos websites e plataformas;</li>
                    <li>Compreender melhor os interesses de nossos clientes e de visitantes do nossos Sites.</li>
                </ul>
                <p><span>Coleta de dados e publicidade personalizada de parceiros.</span> Nossa atuação com publicidade personalizada e empresas de publicidade terceiras tem como objetivo oferecer anúncios sob medida com base no seu histórico de navegação. Redes de publicidade online, plataformas de redes sociais e outros serviços de terceiros têm nossa permissão para coletar informações periódicas a seu respeito e a respeito do modo como você utiliza nossos Sites, incluindo nossos aplicativos móveis. Tais informações permitem a esses terceiros reproduzir ou exibir anúncios no nosso Serviço, em outros websites, aplicativos, serviços ou dispositivos utilizados. Na maioria dos casos, as informações utilizadas para fins de publicidade personalizada são coletadas por meio de tecnologias de rastreamento, tais como cookies, objetos em Flash, beacons, scripts embutidos, kits de software de desenvolvimento para dispositivos móveis, tecnologias de localização geográfica e afins (coletivamente, as “tecnologias de rastreamento”), capazes de reconhecer o dispositivo utilizado e coletar dados como rastreamento de cliques, tipo de navegador, data e horário de visitação, identificadores de dispositivos, tecnologia AdID, geolocalização precisa, entre outras. Poderemos, ainda, compartilhar identificadores comuns de contas (como hashes de endereço eletrônico ou identificação do usuário) com nossos parceiros publicitários de modo a auxiliar a identificação de nossos usuários em diferentes dispositivos. Esses dados são utilizados para oferecer anúncios publicitários mais relevantes aos seus interesses pessoais bem como para fornecer serviços relacionados a publicidade, por exemplo, reportes, atribuição, análises e pesquisas de mercado. Além disso, serviços fornecidos por terceiros, como plataformas de redes sociais, podem ser utilizados para oferecer anúncios personalizados em tais plataformas, compartilhando, para tanto, hashes de e-mail eletrônico ou outras informações com o provedor da plataforma. Consulte a seção “Suas preferências de publicidade” abaixo para saber mais acerca de publicidade personalizada.</p>
                <p><span>Widgets de redes sociais e publicidade.</span> Nosso Serviço pode incluir funcionalidades de redes sociais, como o botão “Curtir” do Facebook, LinkedIn, Snapchat, Instagram, Twitter, entre outras. Essas plataformas poderão reconhecer o usuário e coletar informações a respeito de sua visita a nosso Serviço, utilizar cookies ou empregar outras tecnologias de rastreamento. As interações dos usuários com essas funcionalidades são regidas de acordo com as políticas de privacidade das respectivas plataformas.  </p>
                <p>Os anúncios publicitários personalizados são exibidos em plataformas de redes sociais, como Facebook, Twitter, Instagram, LinkedIn, entre outras. Essas plataformas mantêm programas de publicidade personalizada que nos possibilitam direcionar anúncios para usuários que demonstram interesse em nosso Serviço ou para grupos de usuários com perfis e características semelhantes, pessoais ou comerciais. Pode ocorrer o compartilhamento de identificadores únicos, como hash de endereço eletrônico o  identidade do usuário, com essas plataformas ou, ainda, essas plataformas podem coletar informações de visitantes do nosso website, por meio de pixel próprio, visando direcionar anúncios personalizados para os usuários ou para um público específico nas respectivas plataformas de rede social. Os anúncios são exibidos de acordo com as políticas de privacidade de cada plataforma. Caso você não deseje receber anúncios personalizados nas suas redes sociais, você deve ajustar as preferências de publicidade disponíveis em cada plataforma. Para saber mais a respeito das preferências de publicidade, clique nos links abaixo. Note que os links são apresentados por motivos de comodidade, apenas. Não temos controle sobre conteúdo ou recursos disponibilizados por terceiros e não somos responsáveis por seus atos ou omissões. Contate a respectiva plataforma diretamente em caso de dúvidas, perguntas ou reclamações relacionadas aos seus serviços. </p>
                <ul>
                    <li><span>Facebook.</span> Para saber mais sobre suas preferências de publicidade nas plataformas do Facebook, clique <a href="https://www.facebook.com/help/109378269482053">aqui</a>.</li>
                    <li><span>Twitter.</span> Para saber mais sobre controles de privacidade para anúncios personalizados no Twitter, clique <a href="https://help.twitter.com/en/safety-and-security/privacy-controls-for-tailored-ads">aqui</a>.</li>
                    <li><span>LinkedIn.</span> Para saber mais sobre as preferências de publicidade no LinkedIn, clique <a href="https://www.linkedin.com/psettings/advertising">aqui</a>.</li>
                </ul>
                <p><span>Conexão entre dispositivos.</span> Os diversos dispositivos de um usuário poderão ser conectados entre si a fim de oferecer-lhe anúncios relevantes aos seus interesses. Para tanto, nós e nossos parceiros coletamos informações sobre cada dispositivo a partir do acesso ao Serviço. Além disso, poderemos estabelecer parceria com empresas terceiras que empregam tecnologias de rastreamento ou ferramentas de modelagem estatística a fim de determinar se dois ou mais dispositivos estão conectados a um mesmo usuário ou residência. Pode haver, ainda, compartilhamento de identificadores de contas (como endereço de e-mail ou identidade do usuário) com parceiros publicitários de modo a auxiliar o reconhecimento de um usuário em diversos dispositivos diferentes. Nós e nossos parceiros utilizamos a conexão entre dispositivos com o intuito de oferecer conteúdo e anúncios personalizados, realizar análises e mensurar o desempenho das nossas campanhas publicitárias.</p>
                <p><span>Parceiros.</span> Apresentamos a seguir exemplos de parceiros com os quais colaboramos para oferecer conexão entre dispositivos e/ou serviços publicitários. Essa lista será atualizada quando colaborarmos com novos parceiros que oferecem opções acerca da coleta de informações dos usuários e à medida que houver alterações em nossas parcerias ou que novas tecnologias se tornarem disponíveis. Portanto, é provável que essa lista mude e nem sempre indique nossos parceiros atuais.</p>
                <ul>
                    <li><span id="underscore">Google Analytics e Publicidade.</span>  O Google Analytics é utilizado para reconhecimento do usuário e para conectar dispositivos diferentes quando o usuário visita nosso Site ou Serviço em navegadores ou dispositivos móveis, acessa sua conta no nosso Serviço e interage conosco. Com o objetivo de facilitar o serviço, utilizamos um identificador único, como identificação do usuário ou endereço de e-mail com hash. A ferramenta Google Analytics nos permite uma melhor compreensão da maneira como os usuários interagem com nosso Serviço, possibilitando o oferecimento de conteúdo e anúncios personalizados. Para obter mais informações sobre a coleta e o processamento de informações pelo Google Analytics e para saber como controlar as informações enviadas ao Google, visite a página “Como o Google usa informações de sites ou apps que utilizam nossos serviços”, no endereço:  <a href="file:///C%3A/Users/smg1/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/ZSW31GF3/www.google.com/policies/privacy/partners/">www.google.com/policies/privacy/partners/</a>.  Para saber mais a respeito das opções de desativação do Google Analytics, incluindo o add-on de navegador para desativação do Google Analytics, acesse: <a href="https://tools.google.com/dlpage/gaoptout/">https://tools.google.com/dlpage/gaoptout/</a>.</li>
                    <li>Formatos de publicidade visual e outros recursos avançados podem ser utilizados por meio da ferramenta Google Analytics, como os recursos de remarketing do Google Analytics, recursos do Google Display Network Impression Reporting, recursos de integração do DoubleClick Campaign Manager Integration e relatórios demográficos e interesse do Google Analytics. Esses recursos possibilitam a utilização de cookies próprios (como os criados pelo Google Analytics), de terceiros (como os criados pelo DoubleClick) ou em conjunto para informar, otimizar e exibir anúncios com base em visitas anteriores ao Serviço. Você pode ajustar suas preferências ou desativar os recursos de determinados produtos de publicidade do Google. Para tanto, acesse as preferências de anúncio do Google, no endereço:   <a href="https://google.com/ads/preferences%20">https://google.com/ads/preferences</a>, ou visite os recursos online da NAI, disponível em: <a href="http://www.networkadvertising.org/choices">http://www.networkadvertising.org/choices</a>.</li>
                    <li>Serviços de correspondência de dados, como o LiveRamp, podem ser utilizados para auxiliar-nos a mensurar e analisar a eficiência publicitária bem como a gerar dados para fins de publicidade personalizada. Você pode desabilitar os serviços do LiveRamp no endereço:  <a href="https://liveramp.com/opt_out.">https://liveramp.com/opt_out</a>. </li>
                    <li>Podemos, ainda, utilizer terceiros para nos ajudar a medir a eficiência da Plataforma e avaliar a experiência de compra e navegação de forma a melhorarmos nossos serviços.   Você pode saber mais sobre estes parceiros terceirizados e sobre como fazer o descadastramento acessando os sites. </li>
                </ul>
                <ul id="ul_dentro_ul">
                    <li>1. Critero: <a href="https://www.criteo.com/privacy">https://www.criteo.com/privacy</a></li>
                    <li>2. Verizon: <a href="https://www.verizon.com/about/privacy">https://www.verizon.com/about/privacy</a></li>
                    <li>3. Navegg: <a href="https://www.navegg.com/en/privacy-policy">https://www.navegg.com/en/privacy-policy</a></li>
                    <li>4. Hotjar: <a href="https://www.hotjar.com/legal/policies/privacy/">https://www.hotjar.com/legal/policies/privacy/</a></li>
                </ul>
                <p>O parceiro Rokt pode ser utilizado para exibir ofertas personalizadas de outras marcas em nossos sites. Para saber mais a respeito do Rokt e como desativar as ofertas personalizadas, acesse: <a href="http://www.rokt.com/privacy-policy">www.rokt.com/privacy-policy</a>.</p>
                <p><span>Suas preferências de publicidade - Controle de cookies, tecnologias de rastreamento e cookies em Flash.</span> A maioria dos navegadores permite o ajuste de preferências de modo a: (i) exibir notificação a respeito do recebimento de cookies e permitir ou desativar a sua utilização; (ii) desativar os cookies existentes; e (iii) determinar que o navegador rejeite cookies automaticamente. </p>
                <p>O bloqueio ou a exclusão de cookies poderá impactar negativamente sua experiência na utilização do Serviço, afetando a operação correta de algumas de suas funções e tarefas. Dependendo do seu dispositivo móvel e sistema operacional, nem todas as tecnologias de rastreamento poderão ser bloqueadas ou apagadas. Você pode ajustar as opções de e-mail para impedir o download automático de imagens contendo tecnologias que nos permitem saber se você visualizou ou interagiu como os nossos e-mails.</p>
                <p>O deletar de cookies não removerá os objetos de armazenamento local, como objetos em Flash e em HTML5.  Para saber mais a respeito de objetos em Flash, incluindo acerca do gerenciamento de opções de privacidade e armazenamento de cookies em Flash, acesse o website da Adobe ou clique aqui. Caso você opte por apagar os objetos em Flash dos nossos sites, poderá haver restrição parcial ou completa de acesso e uso dos sites e dos benefícios relacionados às informações e aos serviços oferecidos.</p>
                <p><span>Publicidade personalizada.</span> Para saber mais a respeito de publicidade personalizada e como desativar determinadas opções de publicidade personalizada, visite os recursos online da Network Advertising Initiative, no endereço: <a href="http://www.networkadvertising.org/choices">http://www.networkadvertising.org/choices</a>, , e/ou os recursos da DAA, no endereço: <a href="http://optout.aboutads.info/#!/">www.aboutads.info/choices</a>. Note que a desativação pode não afetar anúncios da internet não baseados em cookies.</p>
                <p><span>Conexão entre dispositivos.</span> Note que a desativação do recebimento de anúncios personalizados por meio dos recursos online da NAI e da DAA se restringe a anúncios exibidos em um navegador ou dispositivo específico. Logo, você ainda poderá receber anúncios personalizados em dispositivos diferentes. Portanto, você deve realizar a desativação em todos os navegadores e dispositivos utilizados.</p>
                <p><span>Publicidade em dispositivos móveis.</span> Você pode restringir as funções de publicidade personalizada em dispositivos móveis. Para tanto, selecione “Restringir rastreamento publicitário” (em sistemas iOS) ou “Desativar anúncios personalizados” (em sistemas Android). Pode-se ainda desativar alguns, mas não todos, anúncios personalizados oferecidos por redes de publicidade móvel: acesse a página http://youradchoices.com/appchoices e baixe o aplicativo AppChoices para dispositivo móvel. Por fim, é possível restringir o uso de dados de localização geográfica para fins publicitários, por meio das opções de localização disponíveis no seu dispositivo. </p>
                <p>Observe que algumas dessas opções podem não funcionar caso o seu navegador não aceite cookies. Portanto, você deverá desativá-las novamente em caso de apagamento dos cookies, alteração das opções do navegador, substituição por navegador ou computador diferente ou utilização de outro sistema operacional.</p>
                <p><span>Seus direitos.</span> Você tem o direito de: (i) confirmar a existência do processamento ou solicitar informações e acesso a todas as informações pessoais que temos sobre você; (ii) solicitar que quaisquer informações pessoais incorretas sejam corrigidas; (iii) solicitar a anonimização, bloqueio ou exclusão de dados desnecessários ou excessivos ou dados processados em desacordo com a lei ou opor-se a determinados tipos de processamento que realizamos com suas informações pessoais (incluindo o direito de cancelar qualquer marketing direto) e retirar qualquer consentimento que você nos tenha concedido; (iv) solicitar que as informações pessoais que temos sobre você sejam excluídas com o seu consentimento; (v) solicitar uma cópia de suas informações pessoais em um formato legível usado comumente (ou solicitar a transferência de suas informações pessoais em tal formato para o provedor de serviços terceirizado); (vi) ser informado sobre as consequências de rejeitar o consentimento; (vii) receber informações sobre entidades públicas e privadas que receberam suas informações; e (viii) solicitar a revisão das decisões com base em processamento automático de dados, como análise de perfil. Embora alguns desses direitos possam ser exercidos por você diretamente por meio de nossos Sites, muitos dos direitos, como os relacionados a solicitações de exclusão de seus dados pessoais, deverão ser enviados a nós por e-mail clicando aqui . Podemos também exigir a verificação de sua identidade para fornecer uma cópia de suas informações, conforme permitido por lei. Observe que existe uma série de limitações a esses direitos e pode haver circunstâncias em que não possamos atender a seu pedido. Você pode alterar suas preferências e/ou desativar o recebimento de cookies clicando nas configurações de cookies na parte inferior da página inicial.</p>
                <h3>ARMAZENAMENTO DE DADOS E TRANSFERÊNCIA PARA OUTRAS JURISDIÇÕES:   SUAS INFORMAÇÕES COLETADAS POR MEIO DE NOSSOS SITES E SERVIÇO PODEM SER ARMAZENADAS E PROCESSADAS NO BRASIL, NOS ESTADOS UNIDOS DA AMÉRICA OU EM QUALQUER OUTRO PAÍS NO QUAL NÓS, NOSSAS AFILIADAS OU PROVEDORES DE SERVIÇOS TEMOS INSTALAÇÕES. QUANDO SUAS INFORMAÇÕES PESSOAIS SÃO ARMAZENADAS E PROCESSADAS FORA DO BRASIL, ELAS PODEM SER ACESSADAS POR AUTORIDADES GOVERNAMENTAIS ESTRANGEIRAS E DE ACORDO COM AS LEIS APLICÁVEIS NA JURISDIÇÃO EM QUE ESTÃO ARMAZENADAS. SE VOCÊ ESTIVER EM UMA REGIÃO COM LEIS QUE REGEM A COLETA E O USO DE DADOS QUE PODEM DIFERIR DA LEI DOS EUA, OBSERVE QUE PODEMOS TRANSFERIR INFORMAÇÕES, INCLUINDO INFORMAÇÕES PESSOAIS, PARA UM PAÍS E JURISDIÇÃO COM DIFERENTES LEIS DE PROTEÇÃO DE DADOS, MAS SEMPRE QUE POSSÍVEL, TOMAREMOS MEDIDAS RAZOÁVEIS PARA GARANTIR QUE SEUS DADOS SEJAM PROTEGIDOS. TAL TRANSFERÊNCIA SERÁ REALIZADA QUANDO PERMITIDA POR LEI OU COM BASE NO SEU CONSENTIMENTO. SE VOCÊ DESEJA OBTER MAIS INFORMAÇÕES SOBRE NOSSAS POLÍTICAS E PRÁTICAS COM RELAÇÃO AO NOSSO USO DE PRESTADORES DE SERVIÇOS FORA DO BRASIL, OU TEM DÚVIDAS SOBRE A COLETA, USO, DIVULGAÇÃO OU ARMAZENAMENTO DE INFORMAÇÕES PESSOAIS POR NOSSOS PRESTADORES DE SERVIÇOS LOCALIZADOS FORA DO BRASIL, ENTRE EM CONTATO CONOSCO USANDO OS LINKS DE CONTATO ABAIXO.</h3>
                <p><span>Privacidade de Crianças.</span> De acordo com a legislação brasileira, não coletamos ou solicitamos intencionalmente quaisquer informações, relacionadas ao Serviço, de menores de 18 anos. Se soubermos que inadvertidamente coletamos informações pessoais de qualquer pessoa menor de 18 anos, excluiremos essas informações o mais rápido possível.  Se você acredita que podemos ter coletado informações de uma pessoa com menos de 18 anos, entre em contato conosco usando as informações de contato abaixo. Se você for menor de 18 anos, não tente se registrar nos Sites ou enviar informações pessoais para nós. </p>
                
            </div>

        </div>
    </body>
</html>