<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <title>Politicas de privacidade</title>
        <link rel="stylesheet" type="text/css" href="site.css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
       <div class="cookeis_anuncios_geral">

            <div class="cookeis_anuncios_topo">
                <a href="index.php"><img src="imagens/seta-esquerda.png"></a>
                <a href="index.php">Voltar para Home</a>
            </div>

            <div id="adendo_img">
                <img src="imagens/logoalien.png">
            </div>

            <div id="politica_cookies_first">
                <h2>Política de Cookies e de Anúncios</h2>
                <p>Última atualização: 16 de junho de 2020</p>
                <h3>Utilização de tecnologias de rastreamento</h3>
            </div>

            <div id="politica_cookie_info">
                <p>Quando você visita nossos Sites e acessa ou utiliza nossos Serviços, lê nossos e-mails ou interage conosco por meio de um computador ou dispositivo móvel, nós e nossos parceiros coletamos automaticamente informações a respeito do acesso e da utilização dos Serviços bem como informações sobre o dispositivo utilizado para acessar os Serviços.</p>
                <p>Essas informações nos permitem aprimorar a sua experiência como cliente. Por exemplo, nós ou nossos parceiros utilizamos tecnologias de rastreamento a fim de:</p>
                <ul>
                    <li>·        Identificar clientes novos e atuais;</li>
                    <li>·        Armazenar senhas de clientes cadastrados em nossos Sites;</li>
                    <li>·        Aprimorar nossos Serviços;</li>
                    <li>·        Oferecer anúncios publicitários personalizados e com base em interesses pessoais (consulte abaixo para obter mais informações a respeito de publicidade personalizada).</li>
                    <li>·        Observar os hábitos e as atividades de navegação em diversos websites e plataformas;</li>
                    <li>·        Compreender melhor os interesses de nossos clientes e de visitantes dos nossos Sites.</li>
                </ul>
                <h3>Coleta de dados e publicidade personalizada de parceiros</h3>
                <p>Nossa atuação com publicidade personalizada e empresas de publicidade terceiras tem como objetivo oferecer anúncios sob medida com base no seu histórico de navegação. Redes de publicidade online, plataformas de redes sociais e outros serviços de terceiros têm nossa autorização para coletar informações periódicas a seu respeito e a respeito do modo como você utiliza nossos Sites, incluindo nossos aplicativos móveis. Tais informações permitem a esses terceiros reproduzir ou exibir anúncios nos nossos Serviços, em outros websites, aplicativos, serviços ou dispositivos utilizados.</p>
                <p>Na maioria dos casos (mas não sempre), as informações utilizadas para fins de publicidade personalizada são coletadas por meio de tecnologias de rastreamento, tais como cookies, objetos em Flash, beacons, scripts embutidos, kits de software de desenvolvimento para dispositivos móveis, tecnologias de localização geográfica e afins (coletivamente, as “tecnologias de rastreamento”), capazes de reconhecer o dispositivo utilizado e coletar dados como rastreamento de cliques, tipo de navegador, data e horário de visitação, identificadores de dispositivos, tecnologia AdID, geolocalização precisa, entre outras.</p>
                <p>Poderemos, ainda, compartilhar identificadores comuns de contas (como hashes de endereço eletrônico ou identificação do usuário) com nossos parceiros publicitários de modo a auxiliar a identificação de nossos usuários em diferentes dispositivos. Esses dados são utilizados para oferecer anúncios publicitários mais relevantes aos seus interesses pessoais bem como para fornecer serviços relacionados a publicidade, por exemplo, reportes, atribuição, análises e pesquisas de mercado. Além disso, serviços fornecidos por terceiros, como plataformas de redes sociais, podem ser utilizados para oferecer anúncios personalizados em tais plataformas. Consulte a seção “Suas preferências de publicidade” abaixo para saber mais acerca de publicidade personalizada.</p>
                <h3>Widgets e publicidade em redes sociais</h3>
                <p>Nossos Serviços podem incluir funcionalidades de redes sociais, como o botão “Curtir” do Facebook, LinkedIn, Snapchat, Instagram, Twitter, entre outras. Essas plataformas poderão reconhecer o usuário e coletar informações a respeito de sua visita a nosso Serviços, utilizar cookies ou empregar outras tecnologias de rastreamento. As interações dos usuários com essas funcionalidades são regidas de acordo com as políticas de privacidade das respectivas plataformas.</p>
                <p>Os anúncios publicitários personalizados são exibidos em plataformas de redes sociais, como Facebook, Twitter, Instagram, LinkedIn, entre outras. Essas plataformas mantêm programas de publicidade personalizada que nos possibilitam direcionar anúncios para usuários que demonstram interesse em nosso Serviços ou para grupos de usuários com perfis e características semelhantes, pessoais ou comerciais. Pode ocorrer o compartilhamento de identificadores únicos, como hash de endereço eletrônico ou identidade do usuário, com essas plataformas ou, ainda, essas plataformas podem coletar informações de visitantes do nosso website, por meio de pixel próprio, visando direcionar anúncios personalizados para os usuários ou para um público específico nas respectivas plataformas de rede social. Os anúncios são exibidos de acordo com as políticas de privacidade de cada plataforma. Caso você não deseje receber anúncios personalizados nas suas redes sociais, você deve ajustar as preferências de publicidade disponíveis em cada plataforma. Para saber mais a respeito das preferências de publicidade, clique nos links abaixo. Note que os links são apresentados por motivos de comodidade, apenas. Não temos controle sobre conteúdo ou recursos disponibilizados por terceiros.</p>
                <ul>
                    <li>o   <span>Facebook.</span> Para saber mais a respeito de suas preferências de publicidade nas plataformas do Facebook, clique <a href="#">aqui</a>.</li>
                    <li>o   <span>Twitter.</span> Para saber mais a respeito dos controles de privacidade relativos a anúncios personalizados no Twitter, clique <a href="#">aqui</a>.</li>
                    <li>o   <span>LinkedIn.</span> Para saber mais a respeito de suas preferências de publicidade no LinkedIn, clique <a href="#">aqui</a>.</li>
                </ul>
                <h3>Conexão entre dispositivos</h3>
                <p>Nós ou nossos parceiros terceirizados, poderemos conectar diversos dispositivos de um usuário entre si a fim de oferecer-lhe anúncios relevantes aos seus interesses. Para tanto, nós e nossos parceiros coletamos informações sobre cada dispositivo a partir do acesso aos Serviços. Além disso, poderemos estabelecer parceria com empresas terceiras que empregam tecnologias de rastreamento ou ferramentas de modelagem estatística a fim de determinar se dois ou mais dispositivos estão conectados a um mesmo usuário ou residência. Pode haver, ainda, compartilhamento de identificadores de contas (como endereço de e-mail ou identidade do usuário) com parceiros publicitários de modo a auxiliar o reconhecimento de um usuário em diversos dispositivos diferentes de nossa parte ou de nossos parceiros .Nós e nossos parceiros utilizamos a conexão entre dispositivos com o intuito de oferecer conteúdo e anúncios personalizados, realizar análises e mensurar o desempenho das nossas campanhas publicitárias.</p>
                <h3>Parceiros</h3>
                <p>Apresentamos a seguir exemplos de parceiros com os quais colaboramos para oferecer conexão entre dispositivos e/ou serviços publicitários. Essa lista será atualizada quando ou se colaborarmos com novos parceiros que oferecem opções acerca da coleta de informações dos usuários e à medida que houver alterações em nossas parcerias ou que novas tecnologias se tornarem disponíveis. Portanto, é provável que essa lista mude e nem sempre indique nossos parceiros atuais.</p>
                <p>·        <span id="underscore">Google Analytics e Publicidade</span>. O Google Analytics é utilizado para reconhecimento do usuário e para conectar dispositivos diferentes quando o usuário visita nosso Site ou Serviços em navegadores ou dispositivos móveis, acessa sua conta nos nossos Serviços e interage conosco. Com o objetivo de facilitar o acesso, utilizamos um identificador único, como identificação do usuário ou endereço de e-mail com hash. A ferramenta Google Analytics nos permite uma melhor compreensão da maneira como os usuários interagem com nossos Serviços, possibilitando o oferecimento de conteúdo e anúncios personalizados. Para obter mais informações sobre a coleta e o processamento de informações pelo Google Analytics e para saber como controlar as informações enviadas ao Google, visite a página “Como o Google usa informações de sites ou apps que utilizam nossos s”, no endereço: <a href="https://policies.google.com/technologies/partner-sites?hl=pt-BR">https://policies.google.com/technologies/partner-sites?hl=pt-BR</a>. Para saber mais a respeito das opções de desativação do Google Analytics, incluindo o add-on de navegador para desativação do Google Analytics, acesse: <a href="https://tools.google.com/dlpage/gaoptout/">https://tools.google.com/dlpage/gaoptout/</a>.</p>
                <p>·        Formatos de publicidade visual e outros recursos avançados podem ser utilizados por meio da ferramenta Google Analytics, como os recursos de Remarketing do Google Analytics, recursos do Google Display Network Impression Reporting, recursos de integração do DoubleClick Campaign Manager Integration e relatórios demográficos e de interesse do Google Analytics. Esses recursos possibilitam a utilização de cookies próprios (como os criados pelo Google Analytics), de terceiros (como os criados pelo DoubleClick) ou em conjunto para informar, otimizar e exibir anúncios com base em visitas anteriores aos Serviços. Você pode ajustar suas preferências ou desativar os recursos de determinados produtos de publicidade do Google. Para tanto, acesse as preferências de anúncio do Google, no endereço: <a href="https://google.com/ads/preferences%20">https://google.com/ads/preferences</a>, ou visite os recursos online da NAI, disponível em: <a href="http://www.networkadvertising.org/choices">http://www.networkadvertising.org/choices</a>. </p>
                <p>·        Serviços de correspondência de dados, como o LiveRamp, podem ser utilizados para auxiliar-nos a mensurar e analisar a eficiência publicitária bem como a gerar dados para fins de publicidade personalizada. Você pode desabilitar os serviços do LiveRamp no endereço: <a href="https://liveramp.com/opt_out.">https://liveramp.com/opt_out </a>.</p>                    
                <p>·        O parceiro Rokt pode ser utilizado para exibir ofertas personalizadas de outras marcas em nossos sites. Para saber mais a respeito do Rokt e como desativar as ofertas personalizadas, acesse: <a href="http://www.rokt.com/privacy-policy">www.rokt.com/privacy-policy</a>. </p>
                <h4>Suas preferências de publicidade</h4>
                <p><span>Controle de cookies, tecnologias de rastreamento e cookies em Flash.</span> A maioria dos navegadores permite o ajuste de preferências de modo a: (i) exibir notificação a respeito do recebimento de cookies e permitir ou desativar a sua utilização; (ii) desativar os cookies existentes; e (iii) determinar que o navegador rejeite cookies automaticamente.</p>
                <p>O bloqueio ou remoção de cookies poderá impactar negativamente sua experiência na utilização dos Serviços, afetando a operação correta de algumas de suas funções e tarefas. Dependendo do seu dispositivo móvel e sistema operacional, nem todas as tecnologias de rastreamento poderão ser bloqueadas ou apagadas. Você pode ajustar as opções de e-mail para impedir o download automático de imagens contendo tecnologias que nos permitem saber se você visualizou ou interagiu como os nossos e-mails.</p>
                <p>O deletar de cookies não removerá os objetos de armazenamento local, como objetos em Flash e em HTML5. Para saber mais a respeito de objetos em Flash, incluindo acerca do gerenciamento de opções de privacidade e armazenamento de cookies em Flash, acesse o website da Adobe ou clique <a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html">aqui</a>. Caso você opte por apagar os objetos em Flash dos nossos sites, poderá haver restrição parcial ou completa de acesso e uso dos sites e dos benefícios relacionados às informações e aos serviços oferecidos.</p>
                <p><span>Publicidade personalizada</span>. Para saber mais a respeito de publicidade personalizada e como desativar determinadas opções de publicidade personalizada, visite os recursos online da Network Advertising Initiative, no endereço: <a href="http://www.networkadvertising.org/choices">http://www.networkadvertising.org/choices</a>, e/ou os recursos da DAA, no endereço: <a href="http://optout.aboutads.info/#!/">www.aboutads.info/choices</a>. Note que a desativação pode não afetar anúncios da internet não baseados em cookies.</p>
                <p><span>Conexão entre dispositivos</span>. Note que a desativação do recebimento de anúncios personalizados por meio dos recursos online da NAI e da DAA se restringe a anúncios exibidos em um navegador ou dispositivo específico. Logo, você ainda poderá receber anúncios personalizados em dispositivos diferentes. Portanto, você deve realizar a desativação em todos os navegadores e dispositivos utilizados.</p>
                <p><span>Publicidade em dispositivos móveis</span>. Você pode restringir as funções de publicidade personalizada em dispositivos móveis. Para tanto, selecione as opções “Restringir rastreamento publicitário” (em sistemas iOS) ou “Desativar anúncios personalizados” (em sistemas Android). Pode-se ainda desativar alguns, mas não todos, anúncios personalizados oferecidos por redes de publicidade móvel: acesse a página <a href="http://youradchoices.com/appchoices">http://youradchoices.com/appchoices</a> e baixe o aplicativo AppChoices para dispositivo móvel. Por fim, é possível restringir o uso de dados de localização geográfica para fins publicitários, por meio das opções de localização disponíveis no seu dispositivo.</p>
                <p>Observe que algumas dessas opções podem não funcionar caso o seu navegador não aceite cookies. Portanto, você deverá desativá-las novamente em caso de apagamento dos cookies, alteração das opções do navegador, substituição por navegador ou computador diferente ou utilização de outro sistema operacional.</p>
            </div>

       </div> 
    </body>
</html>