<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <title>Politicas de privacidade</title>
        <link rel="stylesheet" type="text/css" href="site.css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>

        <div class="termos_uso_geral">

            <<div class="termos_uso_topo">
                <a href="index.php"><img src="imagens/seta-esquerda.png"></a>
                <a href="index.php">Voltar para Home</a>
            </div>

            <div class="privacidade_title">
                <img src="imagens/logoalien.png">
                <h2>TERMOS DE USO E CONDIÇÕES DE PEDIDO</h2>
            </div>

            <div class="termos_conteudo">
                <p>Este Site (“Site”) é operado no Brasil pela <span>PHSR Master Franquia Ltda</span> (“PHSR”, “nós”, “nosso”, “conosco”), uma master franquia da <span>Pizza Hut International LLC</span>, e os termos de uso e condições de pedido (“Termos de Uso e Condições de Pedido”, “Termos de Uso” ou “Termos”) a seguir regem a utilização do Site e dos serviços de informações aqui contidos. Estes Termos de Uso se aplicam a qualquer pessoa (“usuário”, “você”, “seu”, “Cliente”) que utiliza, acessa, consulta, visualiza e/ou baixa as informações disponibilizadas por nós no Site para qualquer finalidade.</p>
                <p>Os termos e condições adicionais de uso aplicáveis a áreas específicas deste Site também podem ser postados em tais áreas e, juntamente com estes Termos de Uso e Condições de Pedido, regem o uso dessas áreas e são incorporados por referência a estes Termos. Os Termos de Uso, juntamente com quaisquer termos e condições adicionais, bem como o Aviso de Privacidade (disponível no Site) são denominados “Contrato”. A PHSR se reserva o direito, a seu critério exclusivo, de alterar ou modificar todo ou parte deste Contrato, a qualquer momento, com validade imediatamente após notificação publicada no site. O uso e uso continuado do site implicam sua aceitação vinculativa deste Contrato, incluindo quaisquer alterações ou modificações feitas pela PHSR conforme permitido acima. Se, a qualquer momento, este Contrato se tornar inaceitável para você, você deverá interromper imediatamente o uso deste site.</p>
                <span>LEIA ATENTAMENTE OS SEGUINTES TERMOS DE USO E CONDIÇÕES DE PEDIDO. O ACESSO E O USO DESTE SITE SÃO SUJEITOS A ESTES TERMOS E CONDIÇÕES. O USO DESTE SITE CONSTITUI SUA ACEITAÇÃO DOS TERMOS E CONDIÇÕES AQUI CONTIDOS. SE VOCÊ NÃO CONCORDAR COM ESSES TERMOS E CONDIÇÕES OU COM QUAISQUER DE SUAS ALTERAÇÕES POSTERIORES, VOCÊ NÃO DEVE, DE FORMA ALGUMA, ACESSAR, VISUALIZAR, UTILIZAR OU CONTINUAR UTILIZANDO ESTE SITE.</span>
                <p>A PHSR, a Pizza Hut International e as lojas Pizza Hut locais estão empenhadas em proteger a privacidade das informações pessoais fornecidas por você em nosso Site. Acreditamos ser importante saber como tratamos as informações que você compartilha conosco. Clique <a href="https://privacy-policy-dev-daumhutnodelivery.web.app/">aqui</a> para visualizar nosso Aviso de Privacidade que está incorporado e faz parte destes Termos de Uso.</p>
                <p>A PHSR poderá revisar, atualizar e/ou alterar periodicamente as informações, serviços e recursos contidos neste Site, e nos reservamos o direito de fazer tais alterações sem obrigação de notificar visitantes anteriores, atuais ou futuros. Sempre que utilizar o site, você será responsável por revisar esses Termos e a Política de Privacidade em caso de quaisquer atualizações ou alterações. O uso continuado deste Site após a publicação de qualquer alteração implicará sua aceitação de quaisquer novos termos ou termos alterados. De forma alguma a PHSR será responsável por qualquer indenização por dano indireto, especial, incidental ou consequencial decorrente de qualquer uso das informações aqui contidas.</p>                    
                <h3>GARANTIA/LIMITAÇÃO DE RESPONSABILIDADE</h3>
                <p>A PHSR se empenha em garantir que as informações contidas neste Site sejam corretas e confiáveis. No entanto, a PHSR e a rede mundial de computadores (ou o host do Site) não são infalíveis e, por vezes, podem ocorrer erros. Portanto, na medida máxima permitida pela legislação aplicável, a PHSR não faz declaração de confiabilidade dos recursos deste Site, do Conteúdo do Site (definido abaixo), do Conteúdo Enviado (definido abaixo) ou de qualquer outro recurso do Site. Você reconhece que esses materiais e/ou sistemas serão utilizados por sua própria conta e risco. A PHSR não é responsável por informações, dados, textos ou outros materiais que possam aparecer no Conteúdo Enviado ou possam de outra forma ser enviados por usuários. As opiniões expressas no Conteúdo Enviado não refletem necessariamente as opiniões da PHSR, e a PHSR não endossa e não tem controle sobre o Conteúdo Enviado. O Conteúdo Enviado não é necessariamente revisado pela PHSR antes da publicação e a PHSR não oferece garantia, expressa ou implícita, quanto ao Conteúdo Enviado ou à precisão e à confiabilidade do Conteúdo Enviado. A PHSR não faz declarações com relação ao período pelo qual qualquer Conteúdo do Site ou Conteúdo Enviado será preservado.</p>
                <p>A PHSR renuncia a qualquer garantia de qualquer tipo, seja expressa ou implícita, quanto a qualquer assunto relacionado a este Site, incluindo, entre outros, a comercialização ou a adequação para qualquer finalidade específica. A PHSR não é responsável por quaisquer danos ou lesões causadas pelo uso deste Site (como vírus, omissões ou distorções). <span>ESTE SITE É FORNECIDO TAL COMO APRESENTADO E DISPONIBILIZADO (“AS-IS”). NENHUMA GARANTIA, EXPRESSA OU IMPLÍCITA, INCLUINDO, ENTRE OUTRAS, A DE COMERCIALIZAÇÃO OU ADEQUAÇÃO PARA UMA FINALIDADE ESPECÍFICA, SERÁ FEITA COM RELAÇÃO A ESTE SITE OU A QUALQUER INFORMAÇÃO OU SOFTWARE NESTE SITE. EM HIPÓTESE ALGUMA, INCLUINDO NEGLIGÊNCIA, A PHSR SERÁ RESPONSÁVEL POR QUALQUER INDENIZAÇÃO POR DANO DIRETO, INDIRETO, INCIDENTAL, ESPECIAL, PUNITIVO OU CONSEQUENCIAL RESULTANTE DA UTILIZAÇÃO OU INCAPACIDADE DE UTILIZAÇÃO DESTE SITE, POR QUAISQUER DANOS RESULTANTES DE ERROS, OMISSÕES, INTERRUPÇÕES, EXCLUSÃO DE ARQUIVOS, DEFEITOS, ATRASOS NA OPERAÇÃO OU TRANSMISSÃO OU QUALQUER FALHA DE DESEMPENHO CAUSADA OU NÃO POR EVENTOS ALÉM DO CONTROLE RAZOÁVEL DA PHSR, INCLUINDO, ENTRE OUTROS, CASOS FORTUITOS, FALHA DA LINHA DE COMUNICAÇÃO, ROUBO, DESTRUIÇÃO OU ACESSO NÃO AUTORIZADO AOS REGISTROS, PROGRAMAS OU SERVIÇOS DO SITE</span>.</p>
                <p>Você entende e concorda que as informações, os detalhes e as descrições mencionadas neste Site, incluindo os detalhes referentes a preços, cardápios, informações nutricionais, produtos e serviços fornecidos no Site (“Produtos”) são apenas para fins informativos e podem ser alterados periodicamente. Portanto, este Site nem sempre contém as informações, detalhes e descrições corretas ou mais atualizadas com relação aos Produtos. Você também reconhece que qualquer orientação nutricional ou qualquer outra orientação incluída no Site não se destina e não constitui orientação profissional ou uma substituição de orientação profissional de qualquer natureza. Essas orientações são de natureza genérica e podem ou não ser aplicáveis ao seu caso, considerando suas condições de saúde. Antes de tomar qualquer medida com base nas orientações do Site, você deve consultar seu médico ou nutricionista para qualquer orientação específica para você. Não seremos responsáveis perante você ou perante qualquer terceiro por inexatidão, integridade ou adequação de tal orientação.</p>
                <p>Embora sejamos responsáveis por manter o Site, não somos responsáveis pela operação das lojas Pizza Hut locais. As lojas Pizza Hut locais são detidas e operadas por outras entidades. Cada loja Pizza Hut local é exclusiva e independentemente responsável pelo relacionamento com seus clientes e por quaisquer questões relacionadas aos serviços por elas prestados.</p>
                <h3>CANAIS DE COMUNICAÇÃO</h3>
                <p>Em determinadas áreas de nosso Site, nosso endereço de e-mail será disponibilizado para que você possa entrar em contato conosco. As informações que você nos fornece por meio deste Site são regidas por nosso Aviso de Privacidade. Essas áreas são destinadas para que os usuários possam entrar em contato conosco com perguntas ou dúvidas. Ao entrar no Site, você reconhece e concorda que quaisquer materiais, ideias, conceitos, técnicas, procedimentos, métodos, sistemas, projetos, planos, gráficos ou materiais semelhantes ou outras comunicações transmitidas para nós em qualquer forma e para qualquer motivo não serão tratadas como confidenciais ou proprietárias. É política da PHSR não devolver quaisquer ideias não solicitadas, conceitos, técnicas, procedimentos, métodos, sistemas, projetos, planos, gráficos ou outros materiais semelhantes. Se você enviar esses materiais, você entende que não tem direitos de propriedade sobre as ideias enviadas e renuncia expressamente a quaisquer direitos ou causas de pedir com relação a qualquer material enviado.</p>
                <h3>DIREITOS DE PROPRIEDADE INTELECTUAL</h3>
                <p>Este Site contém as Marcas Registradas da Pizza Hut (definidas abaixo) utilizadas pela PHSR sob licença da <span>Pizza Hut International LLC</span>. Essas marcas registradas são utilizadas para distinguir produtos e serviços da Pizza Hut. “Marcas Registradas da Pizza Hut” se referem a todos os nomes, marcas, logotipos, designs, aparências do produto, slogans e outras designações que a Pizza Hut utiliza em relação aos seus produtos e serviços. Você não pode, em hipótese alguma, utilizar, remover ou alterar quaisquer Marcas Registradas da Pizza Hut ou associar marcas de seus próprios produtos ou materiais às Marcas Registradas da Pizza Hut. Você reconhece que todos os direitos sobre as Marcas Registradas da Pizza Hut pertencem exclusivamente à <span>Pizza Hut International LLC</span> e concorda que qualquer uso das Marcas Registradas da Pizza Hut por você, se permitido, beneficiará exclusivamente a <span>Pizza Hut International LLC</span>. Você concorda em não incorporar qualquer Marca Registrada da Pizza Hut em suas marcas, nomes de empresas, endereços de internet, nomes de domínio ou quaisquer outras designações semelhantes.</p>
                <p>Da mesma forma, os softwares e a tecnologia utilizados neste Site são operados pela PHSR sob licença da <span>Pizza Hut International LLC</span>. Neste sentido, a <span>Pizza Hut International LLC</span> é a proprietária exclusiva de todos os direitos relacionados aos softwares e a tecnologia utilizados neste Site.</p>
                <p>Este Site e seu conteúdo, incluindo, entre outros, textos, fotografias, gráficos, ilustrações, vídeos, sons e outros materiais (“Conteúdo do Site”) são protegidos sob as leis de direitos de propriedade intelectual relevantes. Eles são utilizados pela PHSR sob licença da <span>Pizza Hut International LLC</span>, que é e deverá permanecer a proprietária exclusiva do Site e de seu conteúdo.</p>
                <p>Qualquer reprodução, modificação, criação de trabalhos derivados ou redistribuição do Site e/ou seu conteúdo é expressamente proibida. A cópia ou a reprodução do Site, de seu conteúdo ou de qualquer parte dele para qualquer outro servidor ou local para reprodução ou redistribuição adicional é expressamente proibida.</p>
                <p>Você não poderá descompilar ou desmontar, fazer engenharia reversa ou de outra forma tentar descobrir qualquer código-fonte relacionado ao Site. Sem limitação ao precedente, você concorda em não reproduzir, duplicar, copiar, vender, revender ou explorar, para qualquer finalidade comercial, qualquer aspecto do Site e/ou seu conteúdo.</p>
                <p>Em todo caso, os direitos de propriedade intelectual sobre quaisquer melhorias nos materiais do site (incluindo software, imagens, Conteúdo do Site e afins) pertencerão à PHSR ou <span>Pizza Hut International LLC</span>, conforme o caso.</p>
                <p>O Conteúdo do Site é protegido contra reprodução e simulação sob as leis nacionais e internacionais e, exceto quando indicado de outra forma, não deve ser copiado, distribuído, exibido, reproduzido ou transmitido de qualquer forma, por qualquer meio, sem a autorização prévia expressa por escrito da PHSR.</p>
                <p>O conteúdo de terceiros, como o conteúdo postado por usuários, incluindo gráficos, videoclipes, imagens, marcas registradas, denominação, personagens e marcas registradas e direitos autorais, é propriedade dos terceiros que comercializam ou licenciam esse conteúdo e é utilizado pela PHSR sujeito a licença ou sujeito às disposições de uso permitido de direitos autorais dos Estados Unidos, lei de marcas registradas e Direito Marcário do Brasil ou conforme permitido sob outra lei aplicável.</p>
                <h3>CONTEÚDO ENVIADO PELO USUÁRIO</h3>
                <p>Em determinadas áreas do nosso Site, você pode enviar textos, arquivos, imagens, fotos, vídeos, sons, obras musicais, obras de autoria, postagens de texto e outros materiais e conteúdo (“Conteúdo Enviado”). Você não tem direitos de propriedade em sua conta ou outro acesso ao Site ou seus recursos, e a PHSR poderá apagar todo o Conteúdo Enviado, a qualquer momento, com ou sem notificação, se a PHSR considerar que você violou esses Termos, a lei ou por qualquer outro motivo. A PHSR não assume responsabilidade por qualquer informação removida de nosso Site e se reserva o direito de restringir permanentemente o acesso ao Site ou a uma conta de usuário.</p>
                <p>Ao publicar, exibir ou de outra forma enviar o Conteúdo Enviado neste Site ou por meio deste Site, você entende e reconhece que quaisquer materiais ou outras comunicações transmitidas em qualquer maneira e por qualquer motivo não serão tratadas como confidenciais ou proprietárias. Além disso, você reconhece e concorda que quaisquer conceitos, técnicas, procedimentos, métodos, sistemas, vídeos, roteiros, músicas, fotografias, projetos, planos, gráficos ou outros materiais transmitidos por você para a PHSR poderão ser utilizados pela PHSR em qualquer lugar, a qualquer momento e por qualquer motivo, sujeito aos seguintes termos:</p>
                <p>Você concede à PHSR uma licença limitada, não exclusiva, sublicenciável, mundial, integralizada, livre de royalties para utilizar, modificar, executar e exibir publicamente, reproduzir e distribuir o Conteúdo Enviado. Esta licença inclui o direito de hospedar, indexar, armazenar em cache, distribuir e marcar qualquer Conteúdo Enviado, bem como o direito de sublicenciar o Conteúdo Enviado a terceiros, incluindo outros usuários, para uso em outras plataformas, como para uso em telefones celulares, em softwares de vídeo ou música.</p>
                <p>Você declara e garante que é o proprietário do Conteúdo Enviado exibido, publicado ou postado por você no Site, que tem o direito de conceder a licença aqui estabelecida e que a exibição, publicação ou postagem de seu Conteúdo Enviado, e nosso uso dele, não viola e não violará os direitos de privacidade, direitos publicitários, direitos autorais, direitos de marcas registradas, direitos de contrato ou quaisquer outros direitos de propriedade intelectual ou outros direitos de qualquer pessoa ou entidade. Você concorda em pagar por todos os royalties, taxas e quaisquer outras quantias devidas a qualquer pessoa em razão de qualquer Conteúdo Enviado exibido, publicado ou postado por você no Site.</p>
                <p>Sua postagem do Conteúdo Enviado fica ainda sujeita às seguintes regras:</p>
                <p>Você não pode postar qualquer conteúdo que, conforme determinado a critério exclusivo da PHSR, seja ilegal, prejudicial, ilícito, difamatório, ofensivo, obsceno, invasivo da privacidade de qualquer pessoa, ameaçador, assediador, abusivo, odioso, racista, infrator, pornográfico, violento ou de outra forma censurável ou impróprio.</p>
                <p>Você não pode postar conteúdo que contenha informações pessoais sobre qualquer indivíduo, viole a privacidade de qualquer outro indivíduo ou entidade ou qualquer coisa que você tenha a obrigação contratual de manter privada ou confidencial. Você concorda que não irá se passar por outra pessoa ou organização, incluindo, entre outros, o pessoal da PHSR. Você ainda concorda que não irá deturpar uma afiliação com outra pessoa ou organização, nem irá postar qualquer conteúdo que contenha comentários caluniosos ou difamatórios sobre outros, ou que infrinja qualquer direito autoral, marca registrada, patente, segredo comercial ou outro direito de propriedade intelectual de um terceiro. Não permitimos atividades que violem direitos autorais e direitos de propriedade intelectual no Site e podemos, a nosso critério exclusivo, remover qualquer conteúdo infrator, caso acreditemos que ele viole os direitos de propriedade intelectual de terceiros ou os nossos próprios.</p>
                <p>Você não pode postar qualquer conteúdo que contenha solicitação comercial de qualquer tipo, incluindo anunciar um produto ou serviço, oferecer um produto ou serviço para venda ou direcionar os visitantes do Site a um local para obter mais informações sobre um produto ou serviço.</p>
                <p>Você não pode postar nenhum software, arquivo ou link para outros sites e você não pode postar conteúdo que contenha vírus, arquivos corrompidos ou qualquer outro software ou programa semelhante que possa afetar de forma desfavorável a operação ou os recursos do Site. Você não pode modificar, de forma alguma, quaisquer especificações, tecnologias ou códigos de aplicativo fornecidos a você pela PHSR ou incorporados no Conteúdo Enviado, a menos que expressamente autorizado por escrito pela PHSR.</p>
                <p>Você não pode compartilhar ou transferir a senha ou outras informações de acesso com qualquer outra parte, temporária ou permanentemente. Você será o único responsável pelo uso de qualquer conta criada, com autorização, neste Site e pela confidencialidade da sua senha. Qualquer utilização indevida da sua conta, incluindo a postagem de conteúdos ofensivos, preconceituosos ou de qualquer outra maneira ilícitos, será atribuível, única e exclusivamente, a você.</p>
                <p>A PHSR não monitora necessariamente quaisquer materiais postados, transmitidos ou comunicados no Site. Se você acredita que algo no Site viola esses Termos, envie-nos uma mensagem por meio de nossa página “Fale Conosco”. Os termos acima não se aplicam a quaisquer ideias ou outras informações não protegidas que você pode enviar para a PHSR, as quais serão regidas pela seção “Comunicação com a PHSR”, acima.</p>
                <h3>ACESSO AO SITE</h3>
                <p>A PHSR concede a você permissão para utilizar o Site conforme estabelecido nestes Termos, desde que: (i) o uso do Site, conforme permitido, seja exclusivamente para seu uso pessoal e não comercial; (ii) você não copie ou distribua qualquer parte do Site em qualquer meio sem a autorização prévia por escrito da PHSR; (iii) você não altere ou modifique qualquer parte do Site, exceto conforme razoavelmente necessário para utilizar o Site para os fins pretendidos; e (iv) você cumpra com as cláusulas e condições desses Termos.</p>
                <p>Para acessar alguns recursos do Site, você precisará criar uma conta. Você nunca poderá utilizar a conta de outra pessoa sem autorização expressa por escrito. Ao criar sua conta, você deve fornecer informações precisas e completas. Você é exclusivamente responsável pela atividade que ocorre em sua conta e deverá manter a senha da sua conta protegida. Você deve notificar a PHSR imediatamente de qualquer violação de segurança ou uso não autorizado de sua conta. Embora a PHSR não seja responsável por perdas causadas por qualquer uso não autorizado de sua conta, você pode ser responsabilizado pelas perdas da PHSR ou outras perdas devido a tal uso não autorizado.</p>
                <p>Você concorda em não utilizar ou executar qualquer sistema automatizado, incluindo, entre outros, “robôs”, “spiders”, “leitores offline” etc., que acesse o Site e envie, em um determinado período de tempo, mais mensagens de solicitação aos servidores da PHSR do que um ser humano pode produzir no mesmo período usando um navegador da Web convencional. Não obstante o precedente, a PHSR autoriza os operadores de serviços públicos de busca a utilizar “spiders” para copiar materiais do Site com o único propósito de criar índices pesquisáveis e publicamente disponíveis dos materiais, mas não caches ou arquivos de tais materiais. A PHSR se reserva o direito de revogar essas exceções de forma geral ou em casos específicos. Você concorda em não coletar do Site informações pessoalmente identificáveis, incluindo nomes de conta, nem utilizar os sistemas de comunicação fornecidos pelo Site para quaisquer fins de solicitação comercial. Você concorda em não fazer ofertas comerciais para quaisquer usuários do Site com relação ao seu Conteúdo Enviado pelo Usuário</p>
                <p>Você concorda que é o único responsável por obter e manter todos os produtos e equipamentos que possam ser necessários para o uso do Site. Você deve sempre providenciar seu próprio hardware, software, modem e acesso à Internet.</p>
                <h3>INDENIZAÇÃO</h3>
                <p>Você concorda em indenizar e isentar a PHSR, suas matrizes, subsidiárias, diretores, funcionários e contratados do Site e cada um de seus diretores, funcionários e representantes de quaisquer reclamações, indenizações e despesas, incluindo honorários advocatícios razoáveis referentes a (i) violação desses Termos por sua parte ou de seus dependentes ou decorrentes do uso do Conteúdo Enviado; (ii) uso e/ou acesso ao Site e compra dos Produtos; e/ou (iii) violação por sua parte de quaisquer direitos da PHSR ou de terceiros, incluindo, entre outros, qualquer direito autoral, marca registrada, segredo comercial ou outros direitos de propriedade intelectual.</p>
                <h3>HYPERLINKS</h3>
                <p>Este Site pode conter links para sites não mantidos pela PHSR ou relacionados a ela, incluindo, entre outras, plataformas de redes sociais. Os links de hipertexto são fornecidos como um serviço aos usuários, tal como apresentados e disponibilizados (“as is”), pois não necessariamente concordamos ou respaldamos tais links, que não são de forma alguma afiliados a este Site ou à PHSR. A PHSR não revisou os sites com hiperlinks para garantir sua adequação. A PHSR não é responsável pelo conteúdo de qualquer outro site. Esses links devem ser acessados por conta e risco do usuário e, se você acessar quaisquer sites de terceiros, poderá estar sujeito aos termos de uso e às políticas adotadas por esses sites de terceiros. A PHSR não declara nem garante o conteúdo, a integridade ou a precisão desses links ou dos sites com hiperlinks para ou a partir deste Site. Além disso, a PHSR não endossa implicitamente sites de terceiros com hiperlinks para ou a partir deste Site.</p>
                <h3>CONDIÇÕES DE PEDIDO (“Condições”)</h3>
                <h3>PEDIDO E ACEITAÇÃO</h3>
                <p>Estas Condições de Pedido se aplicam a todos os pedidos e contratos para o fornecimento de Produtos disponíveis no cardápio para o Cliente. Todos os pedidos de Produtos serão considerados uma oferta realizada pelo Cliente para comprar os Produtos de acordo com estas Condições. Para que tenham efeito, as alterações dessas Condições devem ser feitas por escrito.</p>
                <p>A aceitação dos pedidos de Produtos será concedida a critério exclusivo da PHSR. A aceitação de um pedido ocorre quando você receber uma mensagem na tela confirmando que seu pedido foi realizado. O pedido pode ser recusado sem qualquer motivo.</p>
                <p>Ao fazer o pedido online, com relação às lojas Pizza Hut locais, você reconhece e concorda que a PHSR (a) está apenas facilitando sua transação com a loja Pizza Hut local escolhida para fornecer os Produtos solicitados; (b) não lhe fornecerá quaisquer Produtos; (c) não guarda informações de pagamento e apenas facilita pagamentos online para o benefício da loja Pizza Hut local da qual você encomendou produtos e/ou serviços; e (d) não faz quaisquer declarações ou garantias com relação a quaisquer Produtos fornecidos a você pela loja Pizza Hut local. Você ainda reconhece e concorda que, ao fazer o Pedido online em uma loja Pizza Hut local, você está celebrando um contrato para os itens comprados na loja e não com a PHSR, concordando, ainda, com este Contrato com relação ao uso do Site.</p>
                <h3>PREÇOS E PAGAMENTO</h3>
                <p>Salvo disposição em contrário por escrito, os preços cotados no Site incluem impostos estaduais e municipais aplicáveis sobre vendas. O preço total dos produtos solicitados pode incluir taxas de entrega e outras taxas, de acordo com os termos praticados pela loja Pizza Hut local, conforme aplicável ao fazer o pedido.</p>
                <p>O preço dos Produtos será o cotado no Site no momento em que você confirmar o seu pedido (clicando no botão de finalização de compra), salvo apenas qualquer erro técnico inadvertido, pelo qual a PHSR não será responsável. Os métodos de pagamento aceitáveis são os pagamentos com cartão de débito, cartão de crédito, dinheiro e Pix. Se o método de pagamento escolhido for em dinheiro, o pagamento será feito após o recebimento do seu pedido, tanto para entregas como para viagem.</p>
                <p>Quando o seu pedido for para entrega e o método de pagamento escolhido for cartão de débito/crédito, o valor do seu pedido será cobrado de sua conta no momento em que o pedido for feito.</p>
                <p>Quando o seu pedido for para viagem e o método de pagamento escolhido for cartão de débito/crédito, você poderá pagar no momento em que o pedido é feito ou na retirada, e você será responsável por indicar este detalhe ao fazer o pedido.</p>
                <p>No caso de pagamento por Pix, você deverá realizar o pagamento no momento em que o pedido é efetuado.</p>
                <p>Reservamo-nos o direito de rescindir ou suspender este Contrato com você se seu pagamento for recusado ou se a PHSR tiver motivos plausíveis para acreditar que o pagamento será recusado, em qualquer etapa, sem qualquer indenização a ser devida a você.</p>
                <p>Você pode fazer o pagamento utilizando os métodos listados em nossa tela de pagamento. Se o seu pedido for feito com um cartão de crédito ou débito, certifique-se de que esse cartão seja válido na data de envio do seu pedido.</p>
                <p>Ao inserir o seu código postal no Site, você é automaticamente direcionado para a página do Site referente à sua loja Pizza Hut local. Observe que, no caso de pedidos online, o preço cobrado pode ser diferente do preço dos Produtos pedidos na loja ou por telefone.</p>
                <h3>ALTERAÇÕES NO SEU PEDIDO</h3>
                <p>Se desejar alterar o seu pedido, entre em contato com a loja Pizza Hut local pelo número de telefone incluído no e-mail de confirmação enviado a você ao fazer seu pedido. Se alterar o seu pedido, o preço cobrado será o preço aplicável ao pedido alterado. Se você pagou com o cartão de crédito, a diferença do preço será paga separadamente para a loja Pizza Hut. Observe que, como as promoções ficam disponíveis por tempo limitado, qualquer mudança no seu pedido pode significar que as promoções não estão mais disponíveis.</p>
                <h3>ENTREGA</h3>
                <p>Os prazos de entrega cotados no momento do pedido são apenas aproximados e podem variar. Nosso objetivo, em relação aos pedidos para viagem, é fornecer os Produtos solicitados o mais próximo possível do horário solicitado. O Cliente concorda em aceitar a entrega dos Produtos no horário e no local de entrega acordados. Pedidos de grandes quantidades serão aceitos somente a critério da loja Pizza Hut de onde você está fazendo o pedido. Se você escolheu pela entrega dos Produtos, a loja Pizza Hut local entregará o pedido na entrada principal do endereço de entrega, mas a entrega só será realizada se o entregador e você consentirem. Se alguma condição especial ou autorização de entrada for necessária para que o funcionário da loja Pizza Hut local chegue ao endereço designado, o Cliente deverá, sob sua responsabilidade, fornecer, na medida do possível, toda a assistência a tal funcionário para que os produtos sejam entregues com sucesso. Se você não estiver presente para receber a mercadoria no endereço fornecido em seu pedido, as refeições solicitadas pelo Cliente não serão entregues em outro endereço, e você não será reembolsado, sendo assim cobrado o valor total do seu pedido. Além disso, o Cliente será responsável por todas as responsabilidades legais decorrentes do pedido de uma refeição para um endereço inexistente.</p>
                <p>Os produtos estão sujeitos à disponibilidade. Se os seus produtos não estiverem disponíveis, um produto substituto adequado, de qualidade e preço equivalente pode ser oferecido a você ou podemos entrar em contato com você para informá-lo de que os produtos solicitados não estão disponíveis e podemos perguntar se você gostaria de fazer outro pedido. Tais condições podem afetar o preço a pagar.</p>
                <h3>POLÍTICA DE REEMBOLSO</h3>
                <span>Cancelamento de Pedidos</span>
                <p>Tenha em mente que a preparação do seu pedido pode começar imediatamente após a confirmação do seu pedido. Por esse motivo, não podemos cancelar, reembolsar ou oferecer crédito na loja se você mudar de ideia ou pedir um item por engano após a confirmação do seu pedido (que é validado quando você recebe uma mensagem ou um e-mail de confirmação que seu pedido foi aceito).</p>
                <p>Não obstante o precedente, o cancelamento de um pedido será autorizado sob as seguintes condições:</p>
                <ul>
                    <li>1. Cancelamento devido a falha na transmissão do pedido para a loja Pizza Hut local;</li>
                    <li>2. Cancelamento após a aprovação da loja Pizza Hut devido ao atraso de mais de 30 minutos para entrega dos Produtos solicitados; ou</li>
                    <li>3. Cancelamento devido ao endereço do Cliente não estar dentro das regiões de entrega da loja Pizza Hut local.</li>
                </ul>
                <span>Pedido Incorreto</span>
                <p>Se você receber Produtos diferentes dos constantes na sua nota, ligue para a loja Pizza Hut local assim que perceber que o pedido está incorreto. Você pode solicitar o reembolso em até 30 minutos após o recebimento dos Produtos listados na nota fiscal, registrados na sua loja Pizza Hut local (no caso de pedidos para viagem) ou informados pela empresa responsável pela entrega. A Pizza Hut local reembolsará apenas o produto que foi entregue incorretamente, não todo o pedido.</p>
                <p>Em todos os casos, solicita-se que os Produtos sejam devolvidos nas embalagens originais.</p>
                <span>Pedido Incompleto</span>
                <p>Caso não receba uma parte dos Produtos listados em sua nota, ligue para a loja Pizza Hut local assim que perceber que um item não foi recebido em seu pedido. Você pode solicitar o reembolso em até 30 minutos após o recebimento dos Produtos listados na nota fiscal, registrados na sua loja Pizza Hut local (no caso de pedidos para viagem) ou informados pela empresa responsável pela entrega. A Pizza Hut local reembolsará apenas o produto que foi entregue incorretamente, não todo o pedido.</p>
                <span>Procedimento de estorno</span>
                <p>Em quaisquer das situações, para o reembolso dos valores pagos:</p>
                <p>1. Em cartão, será avaliado se o pagamento foi realizado há mais de 120 (cento e vinte) dias. Caso positivo, não será possível realizar o estorno. Caso negativo, o estorno será realizado na fatura do cartão em que foi realizada a compra.</p>
                <p>2. Via Pix, será avaliado se o pagamento foi realizado há mais de 90 (noventa) dias. Caso positivo, não será possível realizar o estorno. Caso negativo, o estorno será realizado via Pix.</p>
                <p>Para as compras feitas no cartão de crédito, o reembolso será realizado no prazo de 24 (vinte e quatro) horas, ou, em até 30 (trinta) dias, depender do caso.</p>
                <p>Para as compras realizadas via Pix, o reembolso será realizado em até 24 (vinte e quatro) horas do cancelamento.</p>
                <p>No caso de pagamento realizado em dinheiro, o reembolso ocorrerá por meio de crédito em loja.</p>
                <p>Observe que os termos e condições acima mencionados não se aplicam a itens de cortesia, como talheres descartáveis, canudos, guardanapos, etc. Se omitirmos por engano um item de cortesia gratuito, contate-nos para que possamos resolver o problema com nossa equipe. No entanto, não podemos oferecer descontos, reembolsos ou crédito na loja.</p>
                <span>Pedido Cancelado pela Empresa de Entrega</span>
                <p>Caso a empresa de entrega tenha envidado esforços razoáveis para entrar em contato com você após chegar ao endereço informado, mas não tenha obtido sucesso, você não terá direito a reembolso.</p>
                <h3>Exceções</h3>
                <p>Se 25% ou mais do alimento tiver sido consumido ou removido, você não terá direito a desconto, reembolso ou crédito na loja. Se o alimento tiver sido descartado, reembalado ou adulterado, não será possível verificar sua origem ou emissão e não será possível emitir desconto, reembolso ou crédito na loja.</p>
                <h3>Reembolsos do cartão de débito e crédito</h3>
                <p>Os reembolsos para pedidos pagos com cartões de débito ou crédito online levarão aproximadamente 05 dias para serem aprovados e estarão sujeitos às políticas de reembolso adotadas pela respectiva instituição financeira. A PHSR não é responsável por qualquer ato ou omissão da instituição financeira relevante.</p>
                <span>Responsabilidade</span>
                <p>Em todos os casos, a responsabilidade da PHSR será limitada ao valor dos Produtos comprados pelo Cliente, e nenhuma indenização adicional será devida além do reembolso mencionado acima. Além das lojas Pizza Hut locais, nenhuma outra empresa, afiliada, licenciante ou franqueadora da PHSR (incluindo, entre outras, a empresa Yum! Brands, Inc.) será responsável pelos reembolsos mencionados acima ou qualquer outra obrigação assumida pela PHSR ou pelas lojas Pizza Hut locais.</p>
                <h3>Informações de Contato</h3>
                <p>Se desejar solicitar um reembolso, entre em contato com sua loja Pizza Hut pelo telefone indicado no e-mail de confirmação enviado após seu pedido.</p>
                <h3>DISPOSIÇÕES GERAIS</h3>
                <p>Se você tiver uma conta conosco, você poderá cancelá-la acessando a seção indicada no site e suspendendo o uso do Site. Podemos suspender o uso da sua conta e negar acesso a ela, por qualquer motivo, a nosso critério exclusivo. Você concorda que a suspensão de acesso à sua conta pode ser efetuada sem aviso prévio, e reconhece e concorda que podemos desativar ou excluir imediatamente sua conta do nosso Site ou informações relacionadas e/ou barrar qualquer acesso posterior à sua conta. Além disso, você concorda que não seremos responsáveis perante você ou qualquer terceiro pela descontinuação ou encerramento de sua conta.</p>
                <p>Estes Termos constituem o acordo integral referente ao uso do Site e substitui todas as outras comunicações e propostas, sejam eletrônicas, orais ou por escrito, entre você e a PHSR com relação ao Site e os serviços da PHSR. Você e a PHSR reconhecem e concordam que não há parceria formada, e nem você nem a PHSR tem o poder ou a autoridade para obrigar ou vincular a outra parte.</p>
                <p>O descumprimento por parte da PHSR em exercer ou fazer valer qualquer direito ou disposição deste Acordo não constituirá renúncia de tal direito ou disposição. Caso qualquer disposição deste Contrato seja considerada inválida ou inaplicável por um juízo competente, as partes concordam que o tribunal deve se esforçar para dar efeito às intenções originais das partes, conforme contemplado na disposição em questão, e as outras disposições deste Contrato permanecerão em pleno vigor.</p>
                <p>Os softwares que podem estar disponíveis com relação a este Site estão sujeitos aos controles de exportação dos Estados Unidos e do Brasil. Nenhum software pode ser baixado do Site ou de outra forma exportado ou reexportado de modo que viole das leis de exportação dos Estados Unidos e do Brasil. O usuário baixará ou utilizará os softwares por sua conta e risco.</p>
                <p>O descumprimento da PHSR com este Contrato por motivos de caso fortuito, guerra, incêndio, manifestação, terrorismo, terremoto, ações de autoridades governamentais federais, estaduais ou municipais ou por qualquer outro motivo além do controle razoável da PHSR não será considerado uma violação deste Contrato. Se a PHSR deixar de agir em relação a violação por parte sua ou de outra pessoa, em qualquer ocasião, tal fato não implicará renúncia ao seu direito de agir em relação a violações futuras ou semelhantes.</p>
                <p>Os títulos neste Contrato são para fins de conveniência e referência e não limitam ou afetam este Contrato.</p>
                <p>Caso qualquer disposição destes termos de uso seja ilegal, nula ou, por qualquer motivo, inaplicável, essa disposição será considerada independente destes termos de uso e não afetará a validade e aplicabilidade de quaisquer disposições restantes.</p>
                <p>Salvo descrito em contrário, o Conteúdo do Site é disponibilizado apenas para fornecer informações e promover produtos e serviços da Pizza Hut no Brasil. A PHSR opera este site a partir de sua sede em São Paulo, Brasil, e não declara ou garante que o Conteúdo do Site e os produtos e serviços da Pizza Hut descritos neste site são apropriados ou estão disponíveis para uso em outras jurisdições. Se você utilizar este Site em outro país, você será responsável por cumprir com a legislação aplicável.</p>
                <p>Este Contrato será regido e interpretado de acordo com as leis do Brasil, independentemente de conflitos de princípios legais. Caso qualquer parte do Contrato seja ilegal, nula ou inaplicável, tal parte será considerada independente e não afetará a validade e aplicabilidade das disposições restantes. Possíveis provas de uso deste site para fins ilegais serão fornecidas às autoridades policiais. Os produtos e serviços da Pizza Hut estão disponíveis em várias partes do mundo. No entanto, este Site pode descrever produtos e serviços não disponíveis mundialmente.</p>
                <h3>RESOLUÇÃO DE CONFLITOS</h3>
                <p>É nosso objetivo que o Site atenda às suas expectativas. No entanto, pode haver casos em que você tenha um problema ou contestação que precise de atenção especial. Nesses casos, temos o compromisso de trabalhar com você para chegar a uma resolução que o satisfaça; no entanto, isso só poderá ser feito se conhecermos e compreendermos seu problema. Portanto, para qualquer problema ou conflito que você possa ter, você reconhece e concorda que, primeiro, nos dará a oportunidade de resolvê-lo. Isso inclui enviar uma descrição por escrito do seu problema ou conflito, usando o seguinte endereço de e-mail: faleconosco@pizzahut.com.br ou preenchendo um formulário em nossa página “Fale Conosco”.</p>
                <p>Portanto, você concorda em negociar conosco em boa-fé sobre seu problema ou conflito. Isso deve levar a uma resolução, mas se por algum motivo seu problema ou conflito não for resolvido de forma satisfatória dentro de 60 (sessenta) dias após o recebimento de sua descrição por escrito, você concorda com as disposições adicionais de resolução de conflitos abaixo.</p>
                <p>Você concorda que o único e exclusivo fórum e recurso para todos os conflitos e reclamações que não possam ser resolvidos informalmente e que estejam de alguma forma relacionados ou venham a surgir do Site ou destes Termos serão definitivos e vinculantes no Juízo de Direito do Estado de São Paulo.</p>
            </div>


        </div>
        
    </body>
</html>